version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swaps-compute-engine
    image: swaps-compute-engine
    restart: no
    env_file:
      - ./.env